### PR TITLE
Add support for buildpack-installation

### PR DESCRIPTION
**Pull request by benbardin**
As per https://devcenter.heroku.com/articles/platform-api-reference#buildpack-installations

### CODE REVIEW

**Comment by martyzz1** [comment]
Hi Ben, thanks for this...

**Comment by benbardin** [comment]
You're welcome! Anything you want me to fix up here?

**Comment by martyzz1** [comment]
could you add an example usage in https://github.com/martyzz1/heroku3.py/blob/master/heroku3/examples.py

Also could you add a buildpack-installation section to the Readme?

**Comment by benbardin** [comment]
Will-do

**Comment by benbardin** [comment]
Added some documentation, look good?

(Apologies for the spurious white space changes, my editor did that automatically. I can revert those by hand if you like.)

**Comment by martyzz1** [comment]
Great stuff. those whitespaces changes are all good. my usualy editor would do the same...

**Comment by benbardin** [comment]
Thanks! Mind cutting a release for us?

**Comment by martyzz1** [comment]
I can try to do it tonight. in the meantime you could use the github directly by specifying in your requirements.txt

https://github.com/martyzz1/heroku3.py/tarball/b66db87f13db348ebde0685aecf477b414786972#egg=heroku3

**Pull request merged**
